module DeckSeed

  presidents = Deck.create!(subject: 'Presidents', creator_id: 1)
  disney = Deck.create!(subject: 'Disney', creator_id: 2)
  spanish = Deck.create!(subject: 'Spanish', creator_id: 3)
  french = Deck.create!(subject: 'French', creator_id: 4)
  disney_characters = Deck.create!(subject: 'Disney Characters', creator_id: 2)


  presidents.cards.create!(answer: "human or animal teeth; ivory; lead - never wood", question: "At his inauguration, George Washington only had 1 tooth. At different times, he wore dentures. What were his dentures made of?")
  presidents.cards.create!(answer: "John Quincy Adams", question: "A female reporter wanted to get an interview with this President but he refused because she was a woman. Every morning, he would swim naked in the Potomac River. One morning, she sat on his clothes and wouldn’t move until she got the interview. She did. Who was the President?")
  presidents.cards.create!(answer: "Thomas Jefferson", question: "After his inauguration, this President went back to the house for dinner but there were no more seats left. No one offered him a seat but after a while, the wife of a Kentucky senator asked him if he wanted to sit.")
  presidents.cards.create!(answer: "Andrew Jackson", question: "Which President was the 1st to survive an assassination attempt? An unemployed house painter, Richard Lawrence, fired a pistol at him but it misfired. The 2nd pistol did the same. He then ran after Lawrence and beat him with his cane.")
  presidents.cards.create!(answer: "Martin van Buren", question: "Which President and his wife spoke Dutch at home?")
  presidents.cards.create!(answer: "Zachary Taylor", question: "Which President got his nomination for President late because he refused to accept any letters that had him pay postage due?")
  presidents.cards.create!(answer: "John Tyler", question: "After leaving office, who was so poor he was unable to pay a bill for $1.25 until he sold his corn crop?")
  presidents.cards.create!(answer: "cirrhosis of the liver - he drank a lot", question: "What did Franklin Pierce die from?")
  presidents.cards.create!(answer: "Andrew Johnson", question: "Which President did not know how to read, write and do math until his wife taught him?")
  presidents.cards.create!(answer: "throat cancer - he smoked 7-10 cigars a day", question: "What did Ulysses S. Grant die from? What did he do during his life that caused this?")

  disney.cards.create!(answer: "Lucy, Edmund, Peter & Susan Pevensie", question: "What four children are from Finchley?")
  disney.cards.create!(answer: "Valiant", question: "Lofty, Bugsy & Toughwork are feathered friends from what animated feature?")
  disney.cards.create!(answer: "Cinderella", question: "The phrase Bibbidi-Bobbidi-Boo is from a song in what movie?")
  disney.cards.create!(answer: "Maid Marian", question: "In Robin Hood, who does Robin fall in love with?")
  disney.cards.create!(answer: "Oliver and Company", question: "Georgette was a prissy poodle in what Disney feature?")
  disney.cards.create!(answer: "Hades", question: "What character from Disney's Hercules has blue flames as hair?")
  disney.cards.create!(answer: "Pinocchio", question: "In what feature can the song Hi-Diddle-Dee-Dee be heard?")
  disney.cards.create!(answer: "Vixey", question: "Who does Tod fall in love with in the Fox and the Hound?")
  disney.cards.create!(answer: "A.A. Milne", question: "Who wrote the original Winnie the Pooh series")
  disney.cards.create!(answer: "Pipe", question: "In The Little Mermaid, what does Scuttle call a snarfblatt?")

  spanish.cards.create!(answer: "Night", question: "Noche")
  spanish.cards.create!(answer: "Water", question: "Agua")
  spanish.cards.create!(answer: "Locker or Closet", question: "Armario")
  spanish.cards.create!(answer: "4", question: "Cuatro")
  spanish.cards.create!(answer: "1", question: "Uno")
  spanish.cards.create!(answer: "2", question: "Dos")
  spanish.cards.create!(answer: "3", question: "Tres")
  spanish.cards.create!(answer: "5", question: "cinco")
  spanish.cards.create!(answer: "6", question: "seis")
  spanish.cards.create!(answer: "7", question: "siete")

  french.cards.create!(answer: "yes", question: "oui")
  french.cards.create!(answer: "a", question: "un")
  french.cards.create!(answer: "an", question: "une")
  french.cards.create!(answer: "some", question: "des")
  french.cards.create!(answer: "I", question: "je")
  french.cards.create!(answer: "not", question: "pas")
  french.cards.create!(answer: "this", question: "ce")
  french.cards.create!(answer: "no", question: "non")
  french.cards.create!(answer: "me", question: "moi")
  french.cards.create!(answer: "to see", question: "voir")

  disney_characters.cards.create!(answer: "Snow White", question: "The original Disney Princess")
  disney_characters.cards.create!(answer: "Grumpy", question: "The grouchiest dwarf")
  disney_characters.cards.create!(answer: "Queen Grimhilde", question: "Wanted a person's heart in a box")
  disney_characters.cards.create!(answer: "Pinocchio", question: "He wants to be a real boy")
  disney_characters.cards.create!(answer: "Geppetto", question: "The 'father' of the living puppet")
  disney_characters.cards.create!(answer: "Blue Fairy", question: "When you wish upon a star, this female appears")
  disney_characters.cards.create!(answer: "Monstro", question: "The whale that swallowed the puppet")
  disney_characters.cards.create!(answer: "Dumbo", question: "The flying elephant")
  disney_characters.cards.create!(answer: "Bambi", question: "The faun whose mother was killed")
  disney_characters.cards.create!(answer: "Thumper", question: "The rabbit named for his habit")
end

